jobs:
  # We have to put our configurations here, so we can separate the directories
  include:
    - language: node_js
      node_js:
        - "9.11"
      env:
        - COMPONENT=frontend
      cache:
        directories:
          - "frontend/node_modules"
      before_install:
        - cd $COMPONENT
      script:
        - npm run lint
    - language: node_js
      node_js:
        - "9.11"
      env:
        - COMPONENT=notification
      cache:
        directories:
          - "notification/node_modules"
      before_install:
        - cd $COMPONENT
      script:
        - npm run lint
    - language: python
      python:
        - "3.6"
      env:
        - COMPONENT=request
      cache: pip
      before_install:
        - cd $COMPONENT
      install:
        - pip install -r requirements.txt
        - pip install flake8
      script:
        - flake8
        - python -m unittest
    - language: java
      env:
        - COMPONENT=worker
      before_install:
        - cd $COMPONENT
      install:
        - ./gradlew assemble
      script:
        - ./gradlew check
