matrix:
  # We have to put our configurations here, so we can separate the directories
  include:
    - language: node_js
      node_js:
        - "9.11"
      before_script:
        - cd frontend
      script:
        - npm install htmllint-cli eslint
        - ./node_modules/.bin/eslint .
        - ./node_modules/.bin/htmllint .
