sudo: required
services:
  - docker
cache:
  directories:
    - frontend/node_modules
    - frontend/.gradle
    - integration-tests/node_modules
    - integration-tests/.gradle
    - notification/node_modules
    - notification/.gradle
    - .gradle
    - request/.gradle
    - request/build/envs

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
install:
  - ./gradlew assemble
script:
  - ./gradlew check
