sudo: required
services:
  - docker
cache:
  directories:
    - frontend/node_modules
    - integration-tests/node_modules
    - notification/node_modules
    - request/env
    - .gradle

install:
  - ./gradlew assemble
script:
  - ./gradlew check
