matrix:
  # We have to put our configurations here, so we can separate the directories
  include:
    - language: node_js
      node_js:
        - "9.11"
      before_install:
        - cd frontend
      script:
        - npm run lint
cache:
  directories:
    - "frontend/node_modules"
