version: "3.2"

services:
  cache:
    image: redis:3.2.11
    expose:
      - "6379"

  message_queue:
    image: rabbitmq:3.7.4
    hostname: message_queue
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: "message_queue_user"
      RABBITMQ_DEFAULT_PASS: "EJWSYRYNNtqDkd4V"

  request:
    build: ./request/
    depends_on:
      - message_queue
      - cache
    environment:
      DIPECK_MQ_HOST: "message_queue"
      DIPECK_MQ_USER: "message_queue_user"
      DIPECK_MQ_PASS: "EJWSYRYNNtqDkd4V"
      DIPECK_CACHE_HOST: "cache"
    expose:
      - "5000"

  frontend:
    build: ./frontend/
    depends_on:
      - request
      - notification
    ports:
      - "80:80"

  worker:
    build: ./worker/
    depends_on:
      - message_queue
      - cache
    environment:
      DIPECK_MQ_HOST: "message_queue"
      DIPECK_MQ_USER: "message_queue_user"
      DIPECK_MQ_PASS: "EJWSYRYNNtqDkd4V"
      DIPECK_CACHE_HOST: "cache"

  notification:
    build: ./notification/
    depends_on:
      - cache
    expose:
      - "8080"
    environment:
      DIPECK_CACHE_HOST: "cache"
